# Generated by Django 4.0 on 2022-03-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=10000)),
                ('forms', models.CharField(default='', max_length=10000)),
                ('returned', models.IntegerField(default=0)),
                ('not_returned', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='period1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(default='', max_length=10000)),
                ('signedOutTime', models.CharField(default='', max_length=10000)),
                ('signedInTime', models.CharField(default='', max_length=10000)),
                ('Status', models.CharField(default='', max_length=10000)),
                ('Teacher', models.CharField(default='', max_length=1000)),
                ('EachPersonData', models.CharField(default='', max_length=10000)),
                ('studentID', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='period2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(default='', max_length=10000)),
                ('signedOutTime', models.CharField(default='', max_length=10000)),
                ('signedInTime', models.CharField(default='', max_length=10000)),
                ('Status', models.CharField(default='', max_length=10000)),
                ('Teacher', models.CharField(default='', max_length=1000)),
                ('EachPersonData', models.CharField(default='', max_length=10000)),
                ('studentID', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='period3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(default='', max_length=10000)),
                ('signedOutTime', models.CharField(default='', max_length=10000)),
                ('signedInTime', models.CharField(default='', max_length=10000)),
                ('Status', models.CharField(default='', max_length=10000)),
                ('Teacher', models.CharField(default='', max_length=1000)),
                ('EachPersonData', models.CharField(default='', max_length=10000)),
                ('studentID', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='period4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(default='', max_length=10000)),
                ('signedOutTime', models.CharField(default='', max_length=10000)),
                ('signedInTime', models.CharField(default='', max_length=10000)),
                ('Status', models.CharField(default='', max_length=10000)),
                ('Teacher', models.CharField(default='', max_length=1000)),
                ('EachPersonData', models.CharField(default='', max_length=10000)),
                ('studentID', models.BigIntegerField()),
            ],
        ),
    ]
